name: Veerpal Brar
description: "Veerpal's personal website. I write about my technical learnings."
url: https://veerpalbrar.github.io/
author: Veerpal Brar
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
experience: true
projects: true
opensource: true
school: true
blog: true
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
feed:
  posts_limit: 25
paginate: 7
paginate_path: "/blog/page:num/"
gist:
  noscript: false
highlighter: rouge
kramdown:
  input: GFM
  guess_lang: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block: 
      line_numbers: true