name: Veerpal Brar
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
experience: true
projects: true
opensource: true
school: true
blog: true
plugins:
  - jekyll-paginate
paginate: 7
paginate_path: "/blog/page:num/"
gist:
  noscript: false
